# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/system/bt/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/qcom/common/system/bt


PRODUCT_PACKAGES += \
    com.qualcomm.qti.ant@1.0
